// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates a re-order list of items that have dropped below their specified threshold.
 *
 * - generateReorderList - A function that generates the re-order list.
 * - GenerateReorderListInput - The input type for the generateReorderList function.
 * - GenerateReorderListOutput - The return type for the generateReorderList function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateReorderListInputSchema = z.object({
  items: z.array(
    z.object({
      name: z.string().describe('The name of the item.'),
      quantity: z.number().describe('The current quantity of the item.'),
      threshold: z.number().describe('The threshold below which the item needs to be re-ordered.'),
    })
  ).describe('A list of inventory items with their current quantities and reorder thresholds.'),
});

export type GenerateReorderListInput = z.infer<typeof GenerateReorderListInputSchema>;

const GenerateReorderListOutputSchema = z.object({
  reorderList: z.string().describe('A list of items that need to be re-ordered, with their names and current quantities.'),
});

export type GenerateReorderListOutput = z.infer<typeof GenerateReorderListOutputSchema>;

export async function generateReorderList(input: GenerateReorderListInput): Promise<GenerateReorderListOutput> {
  return generateReorderListFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateReorderListPrompt',
  input: {schema: GenerateReorderListInputSchema},
  output: {schema: GenerateReorderListOutputSchema},
  prompt: `You are an inventory management assistant. Generate a re-order list of items that have dropped below their specified threshold.

Items:
{{#each items}}
- Name: {{name}}, Quantity: {{quantity}}, Threshold: {{threshold}}
{{/each}}

Re-order List:
`,
});

const generateReorderListFlow = ai.defineFlow(
  {
    name: 'generateReorderListFlow',
    inputSchema: GenerateReorderListInputSchema,
    outputSchema: GenerateReorderListOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
